Repository ESGI-4IW-groupe6/Unsecure, pull requests merged in 2018-10, with the labels that each got.

#1 add readme.md
  readme.md
Labels: enhancement

#2 add: Code of conduct file
  CODE_OF_CONDUCT.md
Labels: enhancement

#4 add: travis file with php-cs-fixer
  travis.yml
Labels: enhancement

#5 Add : CONTRIBUTING.md
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  readme.md
Labels: enhancement

#6 fix: travis review feature
  .travis.yml
Labels: enhancement

#7 Fix: Cs fixer recommandations
  .php_cs.cache
  .travis.yml
  app/SymfonyRequirements.php
  app/cache/prod/appProdProjectContainer.php
  app/cache/prod/appProdUrlGenerator.php
  app/cache/prod/appProdUrlMatcher.php
  app/cache/prod/classes.php
  app/cache/prod/doctrine/orm/Proxies/__CG__UnsecureBundleEntityComment.php
  app/cache/prod/doctrine/orm/Proxies/__CG__UnsecureBundleEntitySession.php
  app/cache/prod/doctrine/orm/Proxies/__CG__UnsecureBundleEntitySubject.php
  app/cache/prod/doctrine/orm/Proxies/__CG__UnsecureBundleEntityUser.php
  app/cache/prod/translations/catalogue.en.8739602554c7f3241958e3cc9b57fdecb474d508.php
  app/cache/prod/twig/0b/0b23fc69ed31fcdd83287abf429dfd9b603b7175a488f996363d5ce74545a0a1.php
  app/cache/prod/twig/10/10302f41e2b3280278ee87d691e5a68fc38ed1e7d7dc009655f62a1494442153.php
  app/cache/prod/twig/30/30fe4af2fc333f1578d5c2a0c5936f8cb40aaf489d4b225a0ec2686fe4b22b3b.php
  app/cache/prod/twig/3a/3acfb74344beb25d3c52212537ab35462f6ae01f7898f7c80545acb6d26ab9a2.php
  app/cache/prod/twig/64/64a8f331d076c90b001e244b74a28d51dea2f058e33f49a195e26f0e40d1b2df.php
  app/cache/prod/twig/77/775c83e80f4f23e845e018a7edb24e7fa97eab3fed5e36e6f663bf9757d483c0.php
  app/cache/prod/twig/95/95113a6a258a6bf2cb3580d9c2379199faf2de2439d5fce0b79f050d4af78668.php
  app/cache/prod/twig/9e/9e29e71e837f93ebe88346c78c88813720ef37795a596cd8b63b57e878943322.php
  app/cache/prod/twig/c4/c424e65c94d5c081b8025f05045efdc68c092f1cca48cc9114f121f224e3e300.php
  app/cache/prod/twig/e5/e5ec5639f88c0fd81238b872b67a77c4384411777fd893154df11f27f7ca4b98.php
  app/cache/prod/twig/fe/fe47fe680546d2ceaa45bfe434d2b11e76b89e9cbdb451a314c78d13b0ccb4f3.php
  app/check.php
  php-cs-fixer
  src/UnsecureBundle/Controller/ArticleController.php
  src/UnsecureBundle/Controller/ContactController.php
  src/UnsecureBundle/Controller/IndexController.php
  src/UnsecureBundle/Controller/LoginController.php
  src/UnsecureBundle/Entity/Comment.php
  src/UnsecureBundle/Entity/Session.php
  src/UnsecureBundle/Entity/SessionRepository.php
  src/UnsecureBundle/Entity/Subject.php
  src/UnsecureBundle/Entity/SubjectRepository.php
  src/UnsecureBundle/Entity/User.php
  src/UnsecureBundle/Entity/UserRepository.php
  src/UnsecureBundle/Form/Model/Login.php
  src/UnsecureBundle/Form/Type/ContactType.php
  src/UnsecureBundle/Form/Type/LoginType.php
  src/UnsecureBundle/Form/Type/SubjectType.php
  src/UnsecureBundle/Service/LoginService.php
  src/UnsecureBundle/Service/SessionService.php
  travis.yml
Labels: enhancement

#8 feature: Add issue template
  ISSUE_TEMPLATE.md
Labels: enhancement

#11 Improve: Readme tag build
  readme.md
Labels: enhancement

#12 Adding the PR_template
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#13 Updating the "Contributing Section" of the Readme.md
  readme.md
Labels: enhancement

#15 update : readme with the \n
  app/SymfonyRequirements.php
  app/cache/prod/appProdProjectContainer.php
  app/cache/prod/appProdUrlGenerator.php
  app/cache/prod/appProdUrlMatcher.php
  app/cache/prod/classes.php
  app/cache/prod/doctrine/orm/Proxies/__CG__UnsecureBundleEntityComment.php
  app/cache/prod/doctrine/orm/Proxies/__CG__UnsecureBundleEntitySession.php
  app/cache/prod/doctrine/orm/Proxies/__CG__UnsecureBundleEntitySubject.php
  app/cache/prod/doctrine/orm/Proxies/__CG__UnsecureBundleEntityUser.php
  app/cache/prod/twig/10/10302f41e2b3280278ee87d691e5a68fc38ed1e7d7dc009655f62a1494442153.php
  app/cache/prod/twig/3a/3acfb74344beb25d3c52212537ab35462f6ae01f7898f7c80545acb6d26ab9a2.php
  app/cache/prod/twig/64/64a8f331d076c90b001e244b74a28d51dea2f058e33f49a195e26f0e40d1b2df.php
  app/cache/prod/twig/9e/9e29e71e837f93ebe88346c78c88813720ef37795a596cd8b63b57e878943322.php
  app/cache/prod/twig/e5/e5ec5639f88c0fd81238b872b67a77c4384411777fd893154df11f27f7ca4b98.php
  app/check.php
  readme.md
Labels: bug

#17 Add: docker readme informations
  readme.md
Labels: enhancement, good first issue

#19 Update : Readme
  readme.md
Labels: enhancement

#20 Fix : readme
  .DS_Store
  readme.md
Labels: bug

#21 Fix: Readme and contributing
  CONTRIBUTING.md
  readme.md
Labels: bug
